### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by ArifAhmed1995** [Csega/PythonCAD3#1]
Hi,
Thanks for this effort to translate to Python 3 and PyQt5 !

I'm facing the following error when executing `python3 pythoncad_qt.py`

```
Traceback (most recent call last):
  File "pythoncad_qt.py", line 42, in <module>
    w,app = getPythonCAD()
  File "pythoncad_qt.py", line 33, in getPythonCAD
    w = CadWindowMdi()
  File "/home/arif7/Downloads/PythonCAD3-master/Interface/cadwindow.py", line 66, in __init__
    self.__application = Application()
  File "/home/arif7/Downloads/PythonCAD3-master/Generic/application.py", line 48, in __init__
    self.kernel = Document(baseDbName)
  File "/home/arif7/Downloads/PythonCAD3-master/Generic/Kernel/document.py", line 93, in __init__
    self.createConnection(dbPath)
  File "/home/arif7/Downloads/PythonCAD3-master/Generic/Kernel/Db/basedb.py", line 48, in createConnection
    self.__dbConnection = sql.connect(dbPath[0])
sqlite3.OperationalError: unable to open database file

```

**Comment by ArifAhmed1995** [comment]
Okay, I changed line 48 of basedb.py to  `self.__dbConnection = sql.connect(dbPath)`

The application starts but now I get this error when trying to create a new drawing
```
WARNING:DbKernel:SaveEntity : Type <class 'Kernel.settings.Settings'> not supported from pythoncad kernel
Traceback (most recent call last):
  File "/home/arif7/Downloads/PythonCAD3-master/Interface/CmdIntf/cmdaction.py", line 63, in _actionHandler
    self.__function_handler.evaluate(self.__command)
  File "/home/arif7/Downloads/PythonCAD3-master/Interface/CmdIntf/functionhandler.py", line 88, in evaluate
    self._value = self._command_table[command]()
  File "/home/arif7/Downloads/PythonCAD3-master/Interface/cadwindow.py", line 398, in _onNewDrawing
    child = self.createMdiChild()
  File "/home/arif7/Downloads/PythonCAD3-master/Interface/cadwindow.py", line 276, in createMdiChild
    newDoc = self.__application.newDocument()
  File "/home/arif7/Downloads/PythonCAD3-master/Generic/application.py", line 147, in newDocument
    self.addRecentFiles(fileName)
  File "/home/arif7/Downloads/PythonCAD3-master/Generic/application.py", line 102, in addRecentFiles
    self.updateApplicationSetting(objSettings)
  File "/home/arif7/Downloads/PythonCAD3-master/Generic/application.py", line 244, in updateApplicationSetting
    self.kernel.saveEntity(settingObj)  
  File "/home/arif7/Downloads/PythonCAD3-master/Generic/Kernel/document.py", line 233, in saveEntity
    raise TypeError(msg)
TypeError: SaveEntity : Type <class 'Kernel.settings.Settings'> not supported from pythoncad kernel

```

**Comment by Csega** [comment]
Hi ArifAhmed1995!

Sorry for not responding earlier, I've been super busy lately. I commited a new version, could you try out, whether it is working for you? It's a quick fix, but for me, it seems to work.

**Comment by ArifAhmed1995** [comment]
I will test by today and let you know.
Thanks for the new commits :)

**Comment by ArifAhmed1995** [comment]
It works fine. I had to upgrade my version of PyQt5 to get rid of the `PyQt5.sip` import issue.
Thank you :+1:
