### ISSUE TITLE
SaveEntity Error

### ISSUE THREAD

**Issue by ArifAhmed1995** [Csega/PythonCAD3#2]
Hi,

The application opens fine but I am getting the following error when trying to create a new drawing.
```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Warning: unable to set the previews values
Warning: Unable to set state
WARNING:DbKernel:SaveEntity : Type <class 'Kernel.settings.Settings'> not supported from pythoncad kernel
Traceback (most recent call last):
  File "/home/arif7/PythonCAD3-master/Interface/CmdIntf/cmdaction.py", line 63, in _actionHandler
    self.__function_handler.evaluate(self.__command)
  File "/home/arif7/PythonCAD3-master/Interface/CmdIntf/functionhandler.py", line 88, in evaluate
    self._value = self._command_table[command]()
  File "/home/arif7/PythonCAD3-master/Interface/cadwindow.py", line 398, in _onNewDrawing
    child = self.createMdiChild()
  File "/home/arif7/PythonCAD3-master/Interface/cadwindow.py", line 276, in createMdiChild
    newDoc = self.__application.newDocument()
  File "/home/arif7/PythonCAD3-master/Generic/application.py", line 147, in newDocument
    self.addRecentFiles(fileName)
  File "/home/arif7/PythonCAD3-master/Generic/application.py", line 102, in addRecentFiles
    self.updateApplicationSetting(objSettings)
  File "/home/arif7/PythonCAD3-master/Generic/application.py", line 244, in updateApplicationSetting
    self.kernel.saveEntity(settingObj)  
  File "/home/arif7/PythonCAD3-master/Generic/Kernel/document.py", line 232, in saveEntity
    raise TypeError(msg)
TypeError: SaveEntity : Type <class 'Kernel.settings.Settings'> not supported from pythoncad kernel
```

**Comment by Csega** [comment]
Hi,

I try to look on it today. Can you describe the exact steps on how to reproduce this issue?

**Comment by ArifAhmed1995** [comment]
When clicking "New Drawing" from File menu just after the application opens.

**Comment by Kjadim** [comment]
me too

**Comment by Kjadim** [comment]
> Hi,
> 
> I try to look on it today. Can you describe the exact steps on how to reproduce this issue?
